const DISPLAY_ALERT = 'SHOW_ALERT'
const CLEAR_ALERT = 'CLEAR_ALERT'

const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN'
const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'

const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN'
const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'

const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN';
const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

const LOGOUT_USER = 'LOGOUT_USER'

const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

const HANDLE_CHANGE = 'HANDLE_CHANGE';

const CLEAR_VALUES = 'CLEAR_VALUES';

const CREATE_JOB_BEGIN = 'CREATE_JOB_BEGIN';
const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS';
const CREATE_JOB_ERROR = 'CREATE_JOB_ERROR';

const GET_JOBS_BEGIN = 'GET_JOBS_BEGIN';
const GET_JOBS_SUCCESS = 'GET_JOBS_SUCCESS';

const SET_EDIT_JOB = 'SET_EDIT_JOB';

export {
    DISPLAY_ALERT
    ,CLEAR_ALERT
    ,REGISTER_USER_BEGIN
    ,REGISTER_USER_SUCCESS
    ,REGISTER_USER_ERROR
    ,LOGIN_USER_BEGIN
    ,LOGIN_USER_SUCCESS
    ,LOGIN_USER_ERROR
    ,UPDATE_USER_BEGIN
    ,UPDATE_USER_SUCCESS
    ,UPDATE_USER_ERROR
    ,LOGOUT_USER
    ,TOGGLE_SIDEBAR
    ,HANDLE_CHANGE
    ,CLEAR_VALUES
    ,CREATE_JOB_BEGIN
    ,CREATE_JOB_SUCCESS
    ,CREATE_JOB_ERROR
    ,GET_JOBS_BEGIN
    ,GET_JOBS_SUCCESS
    ,SET_EDIT_JOB
}